# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(798, 594)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label_image = QtWidgets.QLabel(self.centralwidget)
        self.label_image.setText("")
        self.label_image.setAlignment(QtCore.Qt.AlignCenter)
        self.label_image.setObjectName("label_image")
        self.gridLayout.addWidget(self.label_image, 0, 0, 1, 4)
        self.pushButton_charger_image = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_charger_image.setObjectName("pushButton_charger_image")
        self.gridLayout.addWidget(self.pushButton_charger_image, 1, 0, 1, 1)
        self.pushButton_predire = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_predire.setObjectName("pushButton_predire")
        self.gridLayout.addWidget(self.pushButton_predire, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 2, 1, 1)
        self.lineEdit_resultat = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_resultat.setObjectName("lineEdit_resultat")
        self.gridLayout.addWidget(self.lineEdit_resultat, 1, 3, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 798, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.pushButton_charger_image.clicked.connect(self.pushButton_charger_image.click)
        self.pushButton_predire.clicked.connect(self.pushButton_predire.click)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_charger_image.setText(_translate("MainWindow", "Charger image"))
        self.pushButton_predire.setText(_translate("MainWindow", "Prédire"))
        self.label.setText(_translate("MainWindow", "Résultat"))
